# Generated by Django 3.0.2 on 2020-02-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('urlid', models.IntegerField(primary_key=True, serialize=False)),
                ('link', models.CharField(default='Not Found', max_length=1000, null=True)),
                ('result', models.CharField(default='Not Found', max_length=100, null=True)),
                ('add', models.CharField(default='Not Found', max_length=1000, null=True)),
                ('org', models.CharField(default='Not Found', max_length=100, null=True)),
                ('city', models.CharField(default='Not Found', max_length=100, null=True)),
                ('state', models.CharField(default='Not Found', max_length=100, null=True)),
                ('country', models.CharField(default='Not Found', max_length=100, null=True)),
                ('dom', models.CharField(default='Not Found', max_length=100, null=True)),
                ('emails', models.CharField(default='Not Found', max_length=100, null=True)),
                ('rank', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserFeedBack',
            fields=[
                ('userid', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('reply', models.TextField()),
                ('replied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
