# Generated by Django 2.2.7 on 2020-02-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200223_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='registrar',
            field=models.CharField(default='Not Found', max_length=100, null=True),
        ),
    ]
