# Generated by Django 3.0 on 2020-01-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200110_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedback',
            name='reply',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
    ]
