# Generated by Django 3.0 on 2020-01-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_userfeedback_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedback',
            name='replied',
            field=models.BooleanField(default=False),
        ),
    ]
