# Generated by Django 2.2.7 on 2020-01-22 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20200122_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='zip',
            new_name='ziip',
        ),
    ]
