# Generated by Django 2.2.7 on 2020-01-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20200122_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='rank',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
