# Generated by Django 2.2.7 on 2020-01-22 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20200122_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='link',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='url',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
