# Generated by Django 2.2.7 on 2020-01-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20200122_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='rank',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='url',
            name='ziip',
            field=models.IntegerField(default=None),
        ),
    ]
