# Generated by Django 2.2.7 on 2020-01-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20200122_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='rank',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='url',
            name='ziip',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
