# Generated by Django 2.2.7 on 2020-01-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20200122_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='rank',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='ziip',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
