# Generated by Django 2.2.7 on 2020-01-22 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20200122_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='add',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='url',
            name='ziip',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
