# Generated by Django 2.2.7 on 2020-01-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20200122_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='add',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='url',
            name='ziip',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
