# Generated by Django 2.2.7 on 2020-01-22 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_auto_20200122_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='ziip',
        ),
    ]
