# Generated by Django 2.2.7 on 2020-01-23 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_auto_20200122_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='add',
            field=models.CharField(default='Not Found', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='city',
            field=models.CharField(default='Not Found', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='country',
            field=models.CharField(default='Not Found', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='dom',
            field=models.CharField(default='Not Found', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='emails',
            field=models.CharField(default='Not Found', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='link',
            field=models.CharField(default='Not Found', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='org',
            field=models.CharField(default='Not Found', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='rank',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='result',
            field=models.CharField(default='Not Found', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='state',
            field=models.CharField(default='Not Found', max_length=100, null=True),
        ),
    ]
