# Generated by Django 2.2.7 on 2020-01-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_auto_20200123_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='id',
        ),
        migrations.AlterField(
            model_name='url',
            name='link',
            field=models.CharField(default='Not Found', max_length=100, primary_key=True, serialize=False),
        ),
    ]
