# Generated by Django 3.0.2 on 2020-01-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_auto_20200123_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfeedback',
            name='id',
        ),
        migrations.AddField(
            model_name='url',
            name='urlid',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='userid',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='url',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='link',
            field=models.CharField(default='Not Found', max_length=1000, null=True),
        ),
    ]
