# Generated by Django 2.2.7 on 2020-01-24 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_auto_20200124_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='urlid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='userid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
